### ISSUE TITLE
Add Damselfly

### ISSUE THREAD

**Issue by Webreaper** [meichthys/foss_photo_libraries#2]
Hi, I'm the developer of Damselfly, and it would be great to get it added here. Wasn't sure if you wanted the details via issue or PR, so I thought I'd start here. 😁

Repo: [https://github.com/Webreaper/Damselfly](https://github.com/Webreaper/Damselfly)
Github Stars: 682
Active Contributors: 1
Source Language: C# / .Net
Licence: GPL 3.0
Automatic Mobile Update: ❌
Cross platform access to photos: ✅8️⃣
LivePhotos Support: ❌
Mobile App: ❌ (planned mobile support here: https://github.com/Webreaper/Damselfly/issues/40)
Photo Sharing: ❌
Docker Installation: ✅8️⃣
Object/Face Recognition: ✅8️⃣
Basic Editing: ❌ (planning to add crop/hue/saturation/rotate/etc later this year)
EXIF data viewing: ✅9️⃣
Multiple User Support: ✅7️⃣ (adding folder-based permissions later this year)

**Other key features you don't call out in your table:**
EXIF data editing: ✅9️⃣
Background Thumbnail gen and indexing (i.e., no need to manually update): ✅9️⃣
Comprehensive Search including free-text on EXIF metadata and various other search types: ✅9️⃣
Desktop App: ✅7️⃣ (provides sync to local laptop)
Export with watermarking and different resolutions: ✅7️⃣

**Comment by meichthys** [comment]
PRs are preferred, but this works too. I'll get it added👍

Looks like a promising project!

**Comment by meichthys** [comment]
Implemented in v1.2.0
