### ISSUE TITLE
Read-only feature

### ISSUE THREAD

**Issue by SEbbaDK** [meichthys/foss_photo_libraries#20]
Some libraries like Photoview work with a read-only photo library, which is pretty important to someone like me where all uploading, editing and restructuring is done by other means.

**Comment by meichthys** [comment]
I like the concept. Are there other names for this type of implementation?
It sounds like this feature might be related to #6

**Comment by SEbbaDK** [comment]
> I like the concept. Are there other names for this type of implementation? It sounds like this feature might be related to #6

Ahh yeah, definitely very much related. Could be a simple "No / Preserves Structure / Support Read-Only Access" trinary state in the overview.
