### ISSUE TITLE
Split the table into categories of features

### ISSUE THREAD

**Issue by zodiacg** [meichthys/foss_photo_libraries#22]
As the number of software and feature grows, the table is becoming too wide and long.

I suggest splitting the table into multiple ones like [Comparison tables in Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_wiki_software)

For example, divide the features into categories like General Information/App or client support/Format support/Functionalities etc, where different softwares are listed as rows.

**Comment by meichthys** [comment]
I thought about this but i'm not sure how to implement it. If I break it up into categories and put the projects on the first column than the projects will show up in multiple categories. This would make it harder to view the full feature set for an individual project. If I were to leave the projects in the first row of each category then it would make it easy to view the full feature set for a project but would still have the problem of the table being too wide.

**Comment by gene1wood** [comment]
Another possible solution to the table being too wide and too long is PR #35

**Comment by meichthys** [comment]
This is definitely a step in the right direction!

**Comment by gene1wood** [comment]
Now that #35 is merged you can see this wider view here : https://meichthys.github.io/foss_photo_libraries/
