### ISSUE TITLE
librephotos has at least some amount of exif support.

### ISSUE THREAD

**Issue by mokahless** [meichthys/foss_photo_libraries#23]
It seems odd to put and "x" when even the issue linked shows that it clearly has some support. Especially since timestamp data is probably the most important, this should probably be bumped to a checkmark with at least a low number like 1 or 2 or something.

**Comment by meichthys** [comment]
Agreed. Thanks for pointing it out 👍
There is more support for EXIF coming to Librephotos soon too. The backend api already supports a significant amount of exif data.
