### ISSUE TITLE
Request for inclusion of "PhotoStructure" and tagging rows

### ISSUE THREAD

**Issue by hmeine** [meichthys/foss_photo_libraries#24]
Based on https://www.reddit.com/r/selfhosted/comments/wp9f72/photo_manager_recommendation/ it would be useful to add PhotoStructure, and apparently being able to read / display hierarchical tags (from Digikam) as OP asked for in that link is a relatively rare feature, so it might be useful as a row as well.

**Comment by meichthys** [comment]
Sounds like a good recommendation. Would you mind submitting a merge request to add photostructure?

**Comment by meichthys** [comment]
After further review, Photostructure (the backend server) does not satisfy the open-source requirement to be included. See here: https://github.com/photostructure/photostructure-for-servers/issues/18
Also, it's not really completely free as most new features will be behind a subscription. 
I have nothing against paid options, but this specific repository aims to highlight free and open source options.
