### ISSUE TITLE
Adding new mobile app for librephotos

### ISSUE THREAD

**Issue by savvasdalkitsis** [meichthys/foss_photo_libraries#25]
[UhuruPhotos](https://github.com/savvasdalkitsis/uhuruphotos-android/) is a third party native android app built for LibrePhotos with many features. It will also soon support backup and sync

(Disclaimer: I am the developer behind the app)

**Comment by meichthys** [comment]
Great Work! I've been following your developments on UhuruPhotos :)
Hopefully an equally active app will be developed for iOS too!

**Comment by meichthys** [comment]
I currently don't have a way to link multiple apps. Do you have a proposed way to link to your UhuruPhotos app without removing the official app?

**Comment by GreatestFool** [comment]
Maybe adding a row for third party clients will do? Though it might be a bit cluttered depending on how it is done.

**Comment by meichthys** [comment]
That seems like a reasonable option.

Currently, all of the features are things that most photo libraries would strive to offer so I am hesitant to add features that are not achievable by the repository owners.

In general, I'm also hesitant to add features that are mutually exclusive. I would like to keep the list limited to features that can all be achieved at the same time. I realize this might not be possible though, so I'm willing to entertain other features.

**Comment by meichthys** [comment]
The UhuruPhotos app is now linked for the Android Mobile app of Librephotos 👍
