### ISSUE TITLE
Add Synology Photos

### ISSUE THREAD

**Issue by sansei** [meichthys/foss_photo_libraries#43]
Application is free, and has no paid subscription.
People when choosing NAS are actually considering DIY build with Photoprism as an alternative to Synology Photos.
I think comparison of features and limitations of Synology Photos with competitors would be very useful.

**Comment by meichthys** [comment]
Is it open source?

**Comment by sansei** [comment]
No. Synology Photos is a native, built-in application available only to Synology NAS. 
My point is that Google Photos and Synology Photos are where people start from and if something doesn't suit them they look for open-source alternatives. This list here is great for choosing an alternative, but what it's missing is a comparison against the 'benchmark' software such as Synology Photos or Google Photos. 
It's a nice comparison, but it doesn't answer the main question: what will I loose if move off Google Photos/Synology Photos to any of these?

**Comment by meichthys** [comment]
I see your point, but the goal of this project is to compare open source projects. If we add google photos, then what else do we add? iCloud Photos, Samsung photos, synology photos, Flickr,slide box, Microsoft photos, Amazon photos, etc.
