### ISSUE TITLE
Assess and add missing libraries from Awesome Privacy

### ISSUE THREAD

**Issue by Frikster** [meichthys/foss_photo_libraries#45]
I believe there is at least one library from [Awesome Privacy](https://github.com/pluja/awesome-privacy#photo-storage) we can add here. Here is what we have missing.

Self-hosted
- [ ] [Photostructure](https://photostructure.com/) - Self-hosted photo library that makes browsing and sharing a lifetime of memories delightful.

Third-party (they all have differing free tiers. This would be a case where the "freeness" row becomes handy)
- [ ] [Crypt.ee](https://crypt.ee/) - A private and encrypted place for all your photos, documents, notes and more.
- [ ] [Ente](https://ente.io/) - End-to-end encrypted storage for photos and videos. Open source clients.
- [ ] [Stingle Photos](https://stingle.org/) - Open source solution that provides strong security, privacy and encryption to backup your photos.

Local
- [ ] [DigiKam](https://www.digikam.org/) - Awesome Professional Photo Management with the Power of Open Source.
- [ ] [Photok](https://github.com/leonlatsch/Photok) - Photok is a free Photo-Safe. It stores your photos encrypted on your device and hides them from others.
- [ ] [ImageGlass](https://imageglass.org/) - ImageGlass is a lightweight software application whose purpose is to help you view images in a clean and intuitive working environment.

**Comment by meichthys** [comment]
I don't have anything against these apps, but this repository is primarily focused on "Free" Open Source Photo Libraries.
I'm not opposed to adding them to the repository, but a pull request would need to be submitted and reviewed first.

These seem to have varying degrees of 'openness' and free tiers. I don't have the time or interest in continuously testing mostly paid apps like these, but with help, I can see the benefit of having these in the list.

**Comment by meichthys** [comment]
DigiKam and Photok seem to be fully 'Free' and Open source, but are slightly different than most other projects in this repository since they are "local" and may not fit the mold of the 'feature set' which revolves around self-hosted options (i.e. docker, web app, etc).

**Comment by Frikster** [comment]
Totally fair compromise, thanx for explaining +1. If I actually end up testing all of them I'll be sure to open a PR.

**Comment by meichthys** [comment]
> Totally fair compromise, thanx for explaining. If I actually end up testing all of them I'll be sure to open a PR.

Awesome. Thanks for understanding! I'll also clarify in the readme that this project primarily focuses on 'gratis' Open Source projects.
